create table if not exists public.ai_model_configs (
  id bigint generated by default as identity primary key,
  use_case text not null,
  provider text not null,
  model_id text not null,
  label text not null,
  priority integer not null default 1,
  enabled boolean not null default true,
  free_tier boolean not null default true,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_model_configs_use_case_check check (use_case in ('crew_certificate', 'cv', 'ship_certificate', 'sms')),
  constraint ai_model_configs_provider_check check (provider in ('google', 'openrouter')),
  constraint ai_model_configs_priority_check check (priority > 0),
  constraint ai_model_configs_unique_model unique (use_case, provider, model_id)
);

create index if not exists ai_model_configs_active_order_idx
  on public.ai_model_configs (use_case, enabled, priority, id);

alter table public.ai_model_configs enable row level security;
revoke all on table public.ai_model_configs from anon, authenticated;
grant select, insert, update, delete on table public.ai_model_configs to service_role;
grant usage, select on sequence public.ai_model_configs_id_seq to service_role;

insert into public.ai_model_configs (use_case, provider, model_id, label, priority, enabled, free_tier)
select use_case, provider, model_id, label, priority, true, true
from (values
  ('crew_certificate', 'google', 'gemini-3.1-flash-lite-preview', 'Gemini 3.1 Flash Lite Preview (AI Studio)', 1),
  ('crew_certificate', 'google', 'gemini-2.5-flash', 'Gemini 2.5 Flash (AI Studio)', 2),
  ('crew_certificate', 'google', 'gemini-3-flash-preview', 'Gemini 3 Flash Preview (AI Studio)', 3),
  ('crew_certificate', 'openrouter', 'google/gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite (OpenRouter)', 4),
  ('crew_certificate', 'openrouter', 'qwen/qwen3-vl-32b-instruct', 'Qwen3 VL 32B Instruct (OpenRouter)', 5),
  ('cv', 'google', 'gemini-3.1-flash-lite-preview', 'Gemini 3.1 Flash Lite Preview (AI Studio)', 1),
  ('cv', 'google', 'gemini-2.5-flash', 'Gemini 2.5 Flash (AI Studio)', 2),
  ('cv', 'google', 'gemini-3-flash-preview', 'Gemini 3 Flash Preview (AI Studio)', 3),
  ('cv', 'openrouter', 'google/gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite (OpenRouter)', 4),
  ('cv', 'openrouter', 'qwen/qwen3-vl-32b-instruct', 'Qwen3 VL 32B Instruct (OpenRouter)', 5),
  ('ship_certificate', 'google', 'gemini-3.1-flash-lite-preview', 'Gemini 3.1 Flash Lite Preview (AI Studio)', 1),
  ('ship_certificate', 'google', 'gemini-2.5-flash', 'Gemini 2.5 Flash (AI Studio)', 2),
  ('ship_certificate', 'google', 'gemini-3-flash-preview', 'Gemini 3 Flash Preview (AI Studio)', 3),
  ('ship_certificate', 'openrouter', 'google/gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite (OpenRouter)', 4),
  ('ship_certificate', 'openrouter', 'qwen/qwen3-vl-32b-instruct', 'Qwen3 VL 32B Instruct (OpenRouter)', 5),
  ('sms', 'google', 'gemini-3.1-flash-lite-preview', 'Gemini 3.1 Flash Lite Preview (AI Studio)', 1),
  ('sms', 'google', 'gemini-2.5-flash', 'Gemini 2.5 Flash (AI Studio)', 2),
  ('sms', 'google', 'gemini-3-flash-preview', 'Gemini 3 Flash Preview (AI Studio)', 3),
  ('sms', 'openrouter', 'google/gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite (OpenRouter)', 4),
  ('sms', 'openrouter', 'qwen/qwen3-vl-32b-instruct', 'Qwen3 VL 32B Instruct (OpenRouter)', 5)
) as seed(use_case, provider, model_id, label, priority)
on conflict (use_case, provider, model_id) do nothing;
